/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Reply = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlumniProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'isApproved' : IDL.Bool,
  'name' : IDL.Text,
  'notable' : IDL.Bool,
  'profession' : IDL.Text,
  'email' : IDL.Text,
  'testimonials' : IDL.Vec(IDL.Text),
  'department' : IDL.Text,
  'batchYear' : IDL.Nat,
});
export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'date' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const EventType = IDL.Variant({
  'upcoming' : IDL.Null,
  'past' : IDL.Null,
  'webinar' : IDL.Null,
  'reunion' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
  'eventType' : EventType,
});
export const PostType = IDL.Variant({
  'job' : IDL.Null,
  'internship' : IDL.Null,
});
export const JobPost = IDL.Record({
  'id' : IDL.Text,
  'postType' : PostType,
  'title' : IDL.Text,
  'postedBy' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'company' : IDL.Text,
  'location' : IDL.Text,
});
export const Thread = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
  'replies' : IDL.Vec(Reply),
});
export const Feedback = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'profession' : IDL.Text,
  'email' : IDL.Text,
  'department' : IDL.Text,
  'batchYear' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReplyToThread' : IDL.Func([IDL.Text, Reply], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlumniProfile' : IDL.Func([AlumniProfile], [], []),
  'createAnnouncement' : IDL.Func([Announcement], [], []),
  'createEvent' : IDL.Func([Event], [], []),
  'createJobPost' : IDL.Func([JobPost], [], []),
  'createThread' : IDL.Func([Thread], [], []),
  'getAllAlumniProfiles' : IDL.Func([], [IDL.Vec(AlumniProfile)], ['query']),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllFeedbacks' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllJobPosts' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
  'getAllSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllThreads' : IDL.Func([], [IDL.Vec(Thread)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchByNameBatchDepartment' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Vec(AlumniProfile)],
      ['query'],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitFeedback' : IDL.Func([Feedback], [], []),
  'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Reply = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlumniProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'isApproved' : IDL.Bool,
    'name' : IDL.Text,
    'notable' : IDL.Bool,
    'profession' : IDL.Text,
    'email' : IDL.Text,
    'testimonials' : IDL.Vec(IDL.Text),
    'department' : IDL.Text,
    'batchYear' : IDL.Nat,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'date' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const EventType = IDL.Variant({
    'upcoming' : IDL.Null,
    'past' : IDL.Null,
    'webinar' : IDL.Null,
    'reunion' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
    'eventType' : EventType,
  });
  const PostType = IDL.Variant({ 'job' : IDL.Null, 'internship' : IDL.Null });
  const JobPost = IDL.Record({
    'id' : IDL.Text,
    'postType' : PostType,
    'title' : IDL.Text,
    'postedBy' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'company' : IDL.Text,
    'location' : IDL.Text,
  });
  const Thread = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
    'replies' : IDL.Vec(Reply),
  });
  const Feedback = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'profession' : IDL.Text,
    'email' : IDL.Text,
    'department' : IDL.Text,
    'batchYear' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReplyToThread' : IDL.Func([IDL.Text, Reply], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlumniProfile' : IDL.Func([AlumniProfile], [], []),
    'createAnnouncement' : IDL.Func([Announcement], [], []),
    'createEvent' : IDL.Func([Event], [], []),
    'createJobPost' : IDL.Func([JobPost], [], []),
    'createThread' : IDL.Func([Thread], [], []),
    'getAllAlumniProfiles' : IDL.Func([], [IDL.Vec(AlumniProfile)], ['query']),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllFeedbacks' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllJobPosts' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
    'getAllSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllThreads' : IDL.Func([], [IDL.Vec(Thread)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchByNameBatchDepartment' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Vec(AlumniProfile)],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitFeedback' : IDL.Func([Feedback], [], []),
    'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };