/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlumniProfile {
  'id' : string,
  'bio' : string,
  'isApproved' : boolean,
  'name' : string,
  'notable' : boolean,
  'profession' : string,
  'email' : string,
  'testimonials' : Array<string>,
  'department' : string,
  'batchYear' : bigint,
}
export interface Announcement {
  'id' : string,
  'title' : string,
  'body' : string,
  'date' : Time,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Event {
  'id' : string,
  'title' : string,
  'date' : Time,
  'description' : string,
  'image' : [] | [ExternalBlob],
  'location' : string,
  'eventType' : EventType,
}
export type EventType = { 'upcoming' : null } |
  { 'past' : null } |
  { 'webinar' : null } |
  { 'reunion' : null };
export type ExternalBlob = Uint8Array;
export interface Feedback {
  'id' : string,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface JobPost {
  'id' : string,
  'postType' : PostType,
  'title' : string,
  'postedBy' : string,
  'description' : string,
  'isActive' : boolean,
  'company' : string,
  'location' : string,
}
export type PostType = { 'job' : null } |
  { 'internship' : null };
export interface Reply {
  'content' : string,
  'author' : string,
  'timestamp' : Time,
}
export interface Thread {
  'id' : string,
  'title' : string,
  'content' : string,
  'author' : string,
  'timestamp' : Time,
  'replies' : Array<Reply>,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'profession' : string,
  'email' : string,
  'department' : string,
  'batchYear' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReplyToThread' : ActorMethod<[string, Reply], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlumniProfile' : ActorMethod<[AlumniProfile], undefined>,
  'createAnnouncement' : ActorMethod<[Announcement], undefined>,
  'createEvent' : ActorMethod<[Event], undefined>,
  'createJobPost' : ActorMethod<[JobPost], undefined>,
  'createThread' : ActorMethod<[Thread], undefined>,
  'getAllAlumniProfiles' : ActorMethod<[], Array<AlumniProfile>>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllFeedbacks' : ActorMethod<[], Array<Feedback>>,
  'getAllJobPosts' : ActorMethod<[], Array<JobPost>>,
  'getAllSubscribers' : ActorMethod<[], Array<string>>,
  'getAllThreads' : ActorMethod<[], Array<Thread>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchByNameBatchDepartment' : ActorMethod<
    [string, bigint, string],
    Array<AlumniProfile>
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitFeedback' : ActorMethod<[Feedback], undefined>,
  'subscribeToNewsletter' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];